version: "3.8"

services:
  database:
    build: ./mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    restart: always
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    ports:
      - 443:443
    restart: always

volumes:
  db:
  wordpress:

networks:
  network:
    driver: bridge